### ISSUE TITLE
I am new to this, can this be used for container stacking problem

### ISSUE THREAD

**Issue by sharmas1ddharth** [1kastner/conflowgen#179]

**Comment by 1kastner** [comment]
Yes, this package was created for that purpose. The result of the generation process are tabular data as depicted [in the documentation](https://conflowgen.readthedocs.io/en/latest/notebooks/first_steps.html#Examining-the-exported-data). It is the task of the user (e.g., you) to assign each of the containers in the list to a container slot. This package just produces these lists as a [matter of separation of concerns](https://conflowgen.readthedocs.io/en/latest/background.html#separated-scenario-generation). It is completely up to the user of the data to set up a model (e.g., a simulation model or mathematical optimization). As the data is exported as CSV, any software should be capable of reading in that data.

**Comment by sharmas1ddharth** [comment]
I have tried to do this by reading the documentation but failed, can you share any guide or tutorial, that'll be really helpful

**Comment by 1kastner** [comment]
You need to bear with the documentation and the academic publications that are mentioned in the documentation for now. One simple rule - if you cannot make sense of the examples I provided, probably this project is not the right tool for you. From your VERY BRIEF description of your objectives, I seriously believe so.
